version: '3'

services:
  php:
    build:
      context: ./docker/php
    volumes:
      - './src:/var/www/html'

  nginx:
    image: nginx:latest
    ports:
      - 8080:80
    volumes:
      - './src:/var/www/html'
      - './docker/nginx/conf.d:/etc/nginx/conf.d'

  postgres:
    image: postgres:latest
    ports:
      - 54321:5432
    environment:
      - POSTGRES_DB=${DB_DATABASE}
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}